### ISSUE TITLE
OS/X patch for EU4?

### ISSUE THREAD

**Issue by lfmaIwTGhr** [goshathebusiness/universal-checksum-patcher#1]
Hi! Here is the Mac eu4 binary for Intel CPUs: https://k2s.cc/file/75a392a7f4e08/eu4.gz

version 1.35.6
original file size 43MB
under `Europa Universalis IV/eu4.app/Contents/MacOS`

Is this right?

**Comment by goshathebusiness** [comment]
@lfmaIwTGhr i drafted a new release with macos support, i think you need to use amd64 version

**Comment by lfmaIwTGhr** [comment]
@goshathebusiness Thanks!!

There is a typo in code: 

`[]string{"E8", "7A", "C5", "76", "01", "89", "01", "89", "C3", "E8",`

I removed duplicated "01", "89" and then it can be applied.

----

But I get the same warning for ironman: `EU4 is running on a mod...` ([screenshot](https://i.imgur.com/MVM1T4Z.png)) (I edited static modifier txt)

**Comment by goshathebusiness** [comment]
@lfmaIwTGhr I released fix to typo, please try to: 1. Run patch two-three times, currently patch stops searching when findes first concurrence. 2. Try to start new game instead of loading save
