### ISSUE TITLE
EU4 linux support broken

### ISSUE THREAD

**Issue by totally0waffle** [goshathebusiness/universal-checksum-patcher#2]
Currently unable to patch eu4 with current release, HOI4 still works

**Comment by goshathebusiness** [comment]
Fixed

**Comment by totally0waffle** [comment]
Reopening this as the patch applies but does not allow achievements

### EU4 ### 
_**Native**_
Patch applies but does not allow the user to get achievements

_**Proton With Windows Patch**_
Patch applies and allows the user to get achievements

### HOI4 ###
_**Both Versions**_
Work as intended

I can provide the files needed if necessary
