### ISSUE TITLE
Linux EU4 patch applies but fails to allow mods

### ISSUE THREAD

**Issue by totally0waffle** [goshathebusiness/universal-checksum-patcher#4]
Testing done as follows

### EU4 ### 
_**Native**_
Patch applies but does not allow the user to get achievements
-Tested running the game vanilla, allows achievements
-Tested with mods (tested using missions expanded), disables achievements

_**Proton With Windows Patch**_
Works as intended

### HOI4 ###
_**Both Versions**_
Work as intended

I can provide the files needed if necessary

**Comment by goshathebusiness** [comment]
Please provide patched eu4 binary for additional research
